
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BIT_XOR = 33;
  public static final int RIGHT_RBRACKET = 41;
  public static final int PLUS_ASSIGN = 25;
  public static final int BIT_NOT = 34;
  public static final int BIT_AND = 31;
  public static final int NOT_EQUAL = 19;
  public static final int GREATER = 20;
  public static final int INT = 6;
  public static final int LESS = 21;
  public static final int MINUS = 13;
  public static final int ID_GLOBAL = 5;
  public static final int NOT = 39;
  public static final int AND = 37;
  public static final int SEMICOLON = 10;
  public static final int NIL = 3;
  public static final int OR = 38;
  public static final int DIV = 15;
  public static final int LESS_EQUAL = 22;
  public static final int PLUS = 12;
  public static final int ASSIGN = 24;
  public static final int EXP = 17;
  public static final int LEFT_RBRACKET = 40;
  public static final int ID = 4;
  public static final int CRLF = 11;
  public static final int EOF = 0;
  public static final int EQUAL = 18;
  public static final int TRUE = 8;
  public static final int GREATER_EQUAL = 23;
  public static final int error = 1;
  public static final int MUL = 14;
  public static final int MOD = 16;
  public static final int DIV_ASSIGN = 28;
  public static final int MOD_ASSIGN = 29;
  public static final int LITERAL = 2;
  public static final int EXP_ASSIGN = 30;
  public static final int FLOAT = 7;
  public static final int MUL_ASSIGN = 27;
  public static final int BIT_SHR = 36;
  public static final int BIT_OR = 32;
  public static final int FALSE = 9;
  public static final int BIT_SHL = 35;
  public static final int MINUS_ASSIGN = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LITERAL",
  "NIL",
  "ID",
  "ID_GLOBAL",
  "INT",
  "FLOAT",
  "TRUE",
  "FALSE",
  "SEMICOLON",
  "CRLF",
  "PLUS",
  "MINUS",
  "MUL",
  "DIV",
  "MOD",
  "EXP",
  "EQUAL",
  "NOT_EQUAL",
  "GREATER",
  "LESS",
  "LESS_EQUAL",
  "GREATER_EQUAL",
  "ASSIGN",
  "PLUS_ASSIGN",
  "MINUS_ASSIGN",
  "MUL_ASSIGN",
  "DIV_ASSIGN",
  "MOD_ASSIGN",
  "EXP_ASSIGN",
  "BIT_AND",
  "BIT_OR",
  "BIT_XOR",
  "BIT_NOT",
  "BIT_SHL",
  "BIT_SHR",
  "AND",
  "OR",
  "NOT",
  "LEFT_RBRACKET",
  "RIGHT_RBRACKET"
  };
}

